-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-09-03 17:31:10 AST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

-- name: Sean Michael
-- id: 32185456
-- tutorial number: 2

DROP TABLE employee;
DROP TABLE team;

CREATE TABLE employee (
    emp_no           NUMBER(5) NOT NULL,
    emp_fname        VARCHAR2(30),
    emp_lname        VARCHAR2(30),
    emp_street       VARCHAR2(50) NOT NULL,
    emp_town         VARCHAR2(30) NOT NULL,
    emp_pcode        CHAR(4) NOT NULL,
    emp_dob          DATE NOT NULL,
    emp_taxno        VARCHAR2(20),
    team_team_no1    NUMBER(3),
    team_team_no     NUMBER(3),
    employee_emp_no  NUMBER(5)
);

COMMENT ON COLUMN employee.emp_no IS
    'employee number';

COMMENT ON COLUMN employee.emp_fname IS
    'employee first name';

COMMENT ON COLUMN employee.emp_lname IS
    'employee last name';

COMMENT ON COLUMN employee.emp_street IS
    'employee address street';

COMMENT ON COLUMN employee.emp_town IS
    'employee address town';

COMMENT ON COLUMN employee.emp_pcode IS
    'employee post code';

COMMENT ON COLUMN employee.emp_dob IS
    'employee date of birth';

COMMENT ON COLUMN employee.emp_taxno IS
    'employee tax number';

COMMENT ON COLUMN employee.team_team_no1 IS
    'team number';

COMMENT ON COLUMN employee.team_team_no IS
    'team number';

COMMENT ON COLUMN employee.employee_emp_no IS
    'employee number';

CREATE UNIQUE INDEX employee__idx ON
    employee (
        team_team_no
    ASC );

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( emp_no );

CREATE TABLE team (
    team_no          NUMBER(3) NOT NULL,
    employee_emp_no  NUMBER(5)
);

COMMENT ON COLUMN team.team_no IS
    'team number';

COMMENT ON COLUMN team.employee_emp_no IS
    'employee number';

CREATE UNIQUE INDEX team__idx ON
    team (
        employee_emp_no
    ASC );

ALTER TABLE team ADD CONSTRAINT team_pk PRIMARY KEY ( team_no );

ALTER TABLE employee
    ADD CONSTRAINT employee_employee FOREIGN KEY ( employee_emp_no )
        REFERENCES employee ( emp_no );

ALTER TABLE team
    ADD CONSTRAINT employee_team FOREIGN KEY ( employee_emp_no )
        REFERENCES employee ( emp_no );

ALTER TABLE employee
    ADD CONSTRAINT employee_teamv1 FOREIGN KEY ( team_team_no )
        REFERENCES team ( team_no );

ALTER TABLE employee
    ADD CONSTRAINT team_employee FOREIGN KEY ( team_team_no1 )
        REFERENCES team ( team_no );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             2
-- CREATE INDEX                             2
-- ALTER TABLE                              6
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
